### ISSUE TITLE
Unknown country germany

### ISSUE THREAD

**Issue by gregbert42** [jef/nvidia-snatcher#662]
Any idea whats going on here? I've also tried DEU

![image](https://user-images.githubusercontent.com/16961761/97887985-e3a4ea80-1d2a-11eb-8c23-72afa81658ca.png)

```
services:
  nvidia:
    container_name: nvidia
    image: ghcr.io/jef/nvidia-snatcher:nightly
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - BROWSER_TRUSTED=true
      - TZ=Europe/Zurich
      - LANG=en_US.UTF-8
      - PGID=1002
      - PUID=1002
      - COUNTRY=Germany
      - STORES=nvidia,amazon-de,notebooksbilliger,proshop-de,saturn,mediamarkt,mindfactory,cyberport,caseking,asus-de,alternate
      - TWILIO_ACCOUNT_SID=[redact]
      - TWILIO_AUTH_TOKEN=[redact]
      - TWILIO_FROM_NUMBER=[redact]
      - TWILIO_TO_NUMBER=[redact]
      - SHOW_ONLY_SERIES=3070
      - LOW_BANDWIDTH="true"

```
